query {
    categories {
        data {
            id
            attributes {
                name
                icon
                img
                description
                slug
            }
        }
    }
}