query($term:String!){
	recipes(filters:{name:{contains:$term}}){
		data{
			id
			attributes{
				name
				category{
					data{
						id
						attributes{
							name
							slug
						}
					}
				}
			}
		}
	}
}