query($id:ID!){
    usersPermissionsUser(id:$id){
        data{
            attributes{
                favorites{
                    data{
                        id
                        attributes{
                            name
                        }
                    }
                }
            }
        }
    }
}